# -*- coding: utf-8 -*-
"""HW4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aj0uii4sBbcJdALt92dXn8NM8YUhZZG7

# HW4_程式練習 (II)

## 題目一 (25%)


以下有一個 list：

```
numbers = [51, 30, 78, 20, 96, 40, 62]
```

### 任務內容
1. 印出該 list 中的第 1 個數字、第 3 個數字與最後一個數字。
2. 印出 list 中的最大值與最小值。
3. 將 list 中的數字由小到大排序後印出。
4. 計算並印出總和與平均值（平均值保留到小數點第 2 位）。
5. 將大於等於 50 的數字存入新的 list，並印出此 list。
"""



"""## 題目二 (25%)

以下為一個包含亞洲國家及其首都的字典，但其中有一些錯誤資訊：

```
asian_countries = {
    'Taiwan': 'Taipei',
    'Japan': 'Tokyo',
    'South Korea': 'Seoul',
    'Myanmar': 'Yangon',
    'Germany': 'Berlin'
    }
```

### 任務內容
1. 將 `asian_countries` 印出來：
```
print('舊字典:', asian_countries)
```
2.  更新 `asian_countries`：
    - 將 Myanmar 的首都更正為 Naypyidaw
    - 將 Germany 從字典中移除
    - 將 Thailand 及其首都 Bangkok 新增到字典中

  ```
  print('新字典:', asian_countries)
  ```
3. 將國家按照字母排序，並將排序後的結果指派給一個變數 `sorted_asian_countries` 。
  ```
  print('排序後新字典:', sorted_asian_countries)
  ```
"""



"""## 題目三 (25%)

班上有 4 位學生，他們分別有 3 科的考試成績，資料如下：

```python
scores = {
    "Linda": [85, 90, 78],
    "Richard": [72, 88, 91],
    "Una": [90, 85, 87],
    "Brian": [60, 75, 70]
}
```

### 任務內容
1. 計算每位學生的平均分數。
2. 根據平均分數，判斷每位學生的成績評語：
  - 平均分數 ≥ 85，評語為「優秀」
  - 平均分數 ≥ 70 且 < 85，評語為「及格」
  - 平均分數 < 70，評語為「需加強」

3. 請印出每位學生的「平均分數」與「評語」。
4. 額外統計：
  - 計算全班的「總平均分數」。
  - 找出「平均分數最高的學生」並印出其姓名與平均分數。



"""



"""## 題目四 (25%)

我們假設一組有效的密碼必須符合以下條件：

- 長度大於 5 個字元
- 必須包含：
   - 大寫英文字母
   - 小寫英文字母
   - 數字
- 不可以有空白  
<br/>

### 任務內容
1. 請針對以上條件，撰寫一個函數 `check_password()`，判斷傳入的字串是否為有效密碼。如果輸入為有效密碼，函數將回傳 `Valid Password`；如果是無效密碼，函數回傳 `INVALID`。
2. 請使用你的函數印出以下結果  
```
check_password("GenAI4Humanities")
check_password("genai4humanities")
check_password("GENAI4HUMANITIES")
check_password("GenAIGenAI")
check_password("GenAI 2025")
check_password("GenAI")
```
"""

